import type { Service, Dentist, Testimonial } from '@/types'

export const clinicData = {
  name: 'Bright Smile Dental',
  tagline: 'Modern Dentistry for Austin Families',
  address: '2847 South Lamar Blvd, Austin, TX 78704',
  phone: '(512) 555-0142',
  email: 'hello@brightsmiledental.com',
  emergencyLine: '(512) 555-0199',
  website: 'https://brightsmiledental.com',
  hours: {
    monday: '8:00 AM – 6:00 PM',
    tuesday: '8:00 AM – 6:00 PM',
    wednesday: '8:00 AM – 6:00 PM',
    thursday: '8:00 AM – 7:00 PM',
    friday: '8:00 AM – 5:00 PM',
    saturday: '9:00 AM – 2:00 PM',
    sunday: 'Closed',
  },
  insurance: [
    'Aetna',
    'Delta Dental',
    'Cigna',
    'MetLife',
    'Humana',
    'Guardian',
    'United Healthcare',
    'Blue Cross Blue Shield',
  ],
  socialLinks: {
    facebook: 'https://facebook.com/brightsmiledental',
    instagram: 'https://instagram.com/brightsmiledental',
    google: 'https://google.com/maps',
  },
}

export const services: Service[] = [
  {
    slug: 'general-dentistry',
    name: 'General Dentistry',
    category: 'family',
    icon: 'tooth',
    shortDescription: 'Comprehensive check-ups, cleanings, and preventive care to keep your smile healthy year-round.',
    description: [
      'Our general dentistry services form the foundation of a lifetime of healthy smiles. We believe that prevention is always better than treatment, which is why we focus on thorough examinations and professional cleanings that catch problems before they become costly.',
      'During your visit, Dr. Sarah Chen or Dr. James Walker will perform a comprehensive oral health evaluation including digital X-rays, gum disease screening, oral cancer screening, and a full tooth-by-tooth assessment. We take time to explain everything we find and create a personalized care plan.',
      'We use the latest diagnostic technology including digital X-rays that emit 90% less radiation than traditional film, intraoral cameras so you can see exactly what we see, and AI-assisted cavity detection for earlier, more accurate diagnoses.',
      'Whether you\'re coming in for your routine six-month cleaning or need a more detailed evaluation, our team makes every visit comfortable, efficient, and informative. We accept most major insurance plans and offer flexible payment options.',
    ],
    startingPrice: '$89',
    priceBreakdown: [
      { label: 'New Patient Exam + X-rays', price: '$89' },
      { label: 'Routine Cleaning (prophylaxis)', price: '$120–$160' },
      { label: 'Deep Cleaning (per quadrant)', price: '$200–$280' },
      { label: 'Fluoride Treatment', price: '$35' },
      { label: 'Dental Sealants (per tooth)', price: '$45–$65' },
    ],
    whatToExpect: [
      'We\'ll review your medical history and discuss any concerns you have about your oral health.',
      'Digital X-rays are taken to check for decay between teeth and below the gumline.',
      'Our hygienist performs a thorough professional cleaning, removing plaque and tartar buildup.',
      'Dr. Chen or Dr. Walker conducts a comprehensive exam, checking teeth, gums, jaw, and soft tissues.',
      'We\'ll walk you through your findings and recommend a personalized treatment plan if needed.',
      'You\'ll leave with a goodie bag and scheduled for your next visit — appointments every 6 months are recommended.',
    ],
    faqs: [
      { question: 'How often should I get a dental check-up?', answer: 'We recommend a professional cleaning and exam every six months for most patients. If you have gum disease, a history of cavities, or certain medical conditions, we may recommend visits every 3–4 months.' },
      { question: 'Does a cleaning hurt?', answer: 'For most patients, a routine cleaning is completely comfortable. If you have sensitive gums or significant tartar buildup, you may feel some pressure or mild sensitivity. Let us know and we\'ll adjust our approach — we also offer numbing gel for sensitive patients.' },
      { question: 'What\'s included in a new patient exam?', answer: 'Your first visit includes a comprehensive health history review, full-mouth digital X-rays, an oral cancer screening, periodontal (gum) assessment, tooth-by-tooth examination, and a personalized treatment plan. It typically takes 60–90 minutes.' },
      { question: 'Does my insurance cover cleanings?', answer: 'Most dental insurance plans cover two preventive cleanings per year at 100%. We accept all major plans including Delta Dental, Aetna, Cigna, and MetLife. Call us and we\'ll verify your benefits before your visit.' },
      { question: 'How do I know if I have a cavity?', answer: 'Early cavities often have no symptoms at all — that\'s why regular X-rays are so important. As they progress, you may notice sensitivity to hot, cold, or sweets, or a visible dark spot. Don\'t wait for pain; it means the cavity has reached the nerve.' },
    ],
  },
  {
    slug: 'cosmetic-dentistry',
    name: 'Cosmetic Dentistry',
    category: 'cosmetic',
    icon: 'sparkles',
    shortDescription: 'Transform your smile with veneers, bonding, and smile makeovers designed around your unique facial features.',
    description: [
      'A beautiful smile is one of the most powerful things you can wear. Our cosmetic dentistry services are designed to enhance what you already have — addressing chips, gaps, staining, and shape irregularities to create a smile that feels authentically yours.',
      'Dr. Sarah Chen has completed advanced training in aesthetic dentistry and uses digital smile design technology to preview your results before any treatment begins. You\'ll know exactly what your new smile will look like before a single tooth is touched.',
      'We offer a full spectrum of cosmetic treatments from simple tooth bonding that can be completed in one visit to comprehensive smile makeovers combining multiple treatments for dramatic transformation. Every plan is customized — we don\'t do cookie-cutter smiles.',
      'Our lab partnerships use only the highest-quality porcelain and ceramic materials. Your veneers and crowns are crafted by master ceramists to match the natural translucency and color of your surrounding teeth. The results are virtually indistinguishable from natural enamel.',
    ],
    startingPrice: '$250',
    priceBreakdown: [
      { label: 'Composite Bonding (per tooth)', price: '$250–$450' },
      { label: 'Porcelain Veneers (per tooth)', price: '$1,200–$1,800' },
      { label: 'Smile Makeover (6-8 teeth)', price: '$6,000–$12,000' },
      { label: 'Gum Contouring', price: '$300–$600' },
      { label: 'Smile Design Consultation', price: 'Complimentary' },
    ],
    whatToExpect: [
      'A complimentary smile design consultation where we discuss your goals and assess your teeth.',
      'Digital photos and impressions are taken for your custom smile preview.',
      'We review your digital smile design together and finalize the treatment plan.',
      'Treatment is scheduled — many cosmetic procedures take just 1–2 appointments.',
      'You leave with a stunning, natural-looking smile and aftercare instructions.',
    ],
    faqs: [
      { question: 'Are veneers permanent?', answer: 'Traditional porcelain veneers require removing a small amount of enamel (usually less than 0.5mm), which makes them permanent in the sense that you\'ll always need veneers on those teeth. However, we also offer minimal-prep and no-prep veneers for suitable candidates. Veneers typically last 10–20 years with proper care.' },
      { question: 'What\'s the difference between veneers and bonding?', answer: 'Bonding uses tooth-colored composite resin applied directly to the tooth — it\'s faster, less expensive, and reversible. Veneers are thin porcelain shells that require slight enamel removal. Bonding is great for minor fixes; veneers offer more dramatic, durable transformation.' },
      { question: 'How long does a smile makeover take?', answer: 'A typical smile makeover takes 2–4 appointments over 3–6 weeks, depending on the number of teeth and treatments involved. We try to minimize the number of visits and the time you spend in temporary restorations.' },
      { question: 'Will my new smile look natural?', answer: 'Absolutely. We use digital smile design to ensure your results complement your facial features, skin tone, and existing teeth. Our ceramists create restorations with the exact shade, translucency, and texture of natural teeth.' },
      { question: 'Is cosmetic dentistry covered by insurance?', answer: 'Most cosmetic procedures are not covered by insurance as they\'re considered elective. However, some treatments like bonding to repair a chipped tooth may be partially covered. We offer CareCredit and in-house financing to make treatments accessible.' },
    ],
  },
  {
    slug: 'teeth-whitening',
    name: 'Teeth Whitening',
    category: 'cosmetic',
    icon: 'sun',
    shortDescription: 'Professional in-office whitening that\'s up to 8 shades brighter in a single 60-minute appointment.',
    description: [
      'A brighter smile is one of the fastest ways to look younger and more confident. Our professional teeth whitening delivers results that are simply impossible to achieve with over-the-counter products — we use prescription-strength whitening agents in a controlled, safe environment.',
      'We offer two options: in-office Zoom! whitening for immediate results in about an hour, and custom take-home trays for gradual brightening at your convenience. Many patients combine both for faster initial results and ongoing maintenance.',
      'Before any whitening treatment, we ensure your teeth and gums are healthy. We also take a shade reading and photograph your starting point so you can see exactly how far you\'ve come. Sensitivity is common but temporary — we use desensitizing agents to minimize discomfort.',
      'Results from professional whitening typically last 1–3 years with proper maintenance. We\'ll send you home with touch-up trays and whitening gel to keep your smile looking its best between treatments.',
    ],
    startingPrice: '$299',
    priceBreakdown: [
      { label: 'In-Office Zoom! Whitening', price: '$499' },
      { label: 'Custom Take-Home Trays + Gel', price: '$299' },
      { label: 'Combo (In-Office + Take-Home)', price: '$649' },
      { label: 'Whitening Gel Refills', price: '$45' },
    ],
    whatToExpect: [
      'A pre-whitening exam to ensure your teeth and gums are healthy and ready for treatment.',
      'Your current shade is recorded so we can measure your results.',
      'A protective barrier is applied to your gums before the whitening gel is placed.',
      'The whitening gel is activated with a specialized light and applied in three 15-minute sessions.',
      'We remove the gel, rinse, and reveal your new, brighter smile.',
      'You\'ll receive take-home trays and aftercare instructions.',
    ],
    faqs: [
      { question: 'How much whiter will my teeth get?', answer: 'Most patients achieve 4–8 shades brighter with in-office Zoom! whitening. Results vary based on the original shade and type of staining. We\'ll give you a realistic expectation during your consultation.' },
      { question: 'Is teeth whitening safe?', answer: 'Yes, professional whitening is very safe when performed under dental supervision. The procedure uses carbamide or hydrogen peroxide which temporarily opens enamel pores to lift stains. There\'s no damage to your teeth when done properly.' },
      { question: 'Will whitening work on crowns, veneers, or bonding?', answer: 'Whitening only works on natural tooth enamel. It will not change the color of dental restorations. If you have visible restorations, we\'ll discuss whether they need to be replaced to match your new, whiter smile.' },
      { question: 'How long do results last?', answer: 'Professional whitening results typically last 1–3 years, depending on your diet and habits. Coffee, tea, red wine, and tobacco accelerate staining. Regular touch-ups with our take-home gel can extend results significantly.' },
      { question: 'Will my teeth be sensitive afterward?', answer: 'Mild to moderate sensitivity is common for 24–48 hours after whitening. We use desensitizing agents during treatment and recommend using sensitive toothpaste for a week before and after. Sensitivity is temporary and resolves completely.' },
    ],
  },
  {
    slug: 'invisalign',
    name: 'Invisalign',
    category: 'cosmetic',
    icon: 'aligncenter',
    shortDescription: 'Straighten your teeth discreetly with clear aligners custom-made for your smile — no metal, no brackets.',
    description: [
      'Invisalign has transformed orthodontic treatment for millions of adults and teens who want straight teeth without the look and feel of traditional braces. The system uses a series of custom, removable clear aligners that gradually shift your teeth into their ideal position.',
      'Dr. Sarah Chen is a certified Invisalign provider with experience treating mild to complex cases including crowding, spacing, overbite, underbite, and crossbite. We use iTero 3D digital scanning — no messy impressions — to create a precise treatment plan and digital preview of your results.',
      'Invisalign aligners are virtually invisible, removable for eating and brushing, and gentler on your gums and cheeks than metal braces. Most adult cases are completed in 12–18 months, and you\'ll visit us just every 6–8 weeks to check your progress.',
      'We offer Invisalign for adults, Invisalign Teen (with compliance indicators and replacement aligners), and Invisalign Lite for minor corrections. Every plan includes retainers after treatment to preserve your results for life.',
    ],
    startingPrice: '$3,500',
    priceBreakdown: [
      { label: 'Invisalign Lite (minor corrections)', price: '$3,500–$4,500' },
      { label: 'Invisalign Full (comprehensive)', price: '$5,500–$7,500' },
      { label: 'Invisalign Teen', price: '$5,000–$7,000' },
      { label: 'Retainers (after treatment)', price: '$350–$500' },
      { label: '3D Scan & Treatment Preview', price: 'Complimentary' },
    ],
    whatToExpect: [
      'A complimentary consultation including a 3D iTero scan of your teeth.',
      'We create a digital ClinCheck treatment plan showing the step-by-step movement of your teeth.',
      'You approve the plan and your custom aligners are manufactured — usually 2–3 weeks.',
      'You receive your first sets of aligners and wear each for 1–2 weeks, 20–22 hours per day.',
      'Check-in appointments every 6–8 weeks to monitor progress and give you the next batch of aligners.',
      'After your final aligner, you\'ll receive permanent retainers to lock in your new smile.',
    ],
    faqs: [
      { question: 'Am I a candidate for Invisalign?', answer: 'Most people with crowding, spacing, or mild-to-moderate bite issues are good Invisalign candidates. Complex cases may still require traditional braces. A free consultation with Dr. Chen will determine the best approach for your specific situation.' },
      { question: 'How long does Invisalign take?', answer: 'Mild cases can be corrected in as little as 6 months with Invisalign Lite. Comprehensive cases typically take 12–18 months. Teen cases average 12–18 months as well. The exact timeline depends on the complexity of your case and how consistently you wear your aligners.' },
      { question: 'How many hours per day must I wear the aligners?', answer: 'Invisalign works best when worn 20–22 hours per day. You remove them to eat, drink anything other than water, brush, and floss. The discipline required is the main difference between a successful outcome and a prolonged treatment.' },
      { question: 'Does Invisalign hurt?', answer: 'You\'ll feel pressure and mild soreness for 1–3 days after switching to a new aligner — this means it\'s working. This discomfort is generally less intense than the soreness patients experience after traditional braces adjustments. Over-the-counter pain relievers help.' },
      { question: 'Does insurance cover Invisalign?', answer: 'Many dental insurance plans cover Invisalign just like they cover traditional orthodontics, typically $1,000–$3,000 toward treatment. We\'ll verify your benefits before you commit to any treatment plan. We also offer 0% financing through CareCredit.' },
    ],
  },
  {
    slug: 'dental-implants',
    name: 'Dental Implants',
    category: 'specialty',
    icon: 'anchor',
    shortDescription: 'Permanent tooth replacement that looks, feels, and functions exactly like your natural teeth.',
    description: [
      'Dental implants are the gold standard for replacing missing teeth. Unlike dentures or bridges, implants integrate directly with your jawbone, creating a stable foundation that prevents bone loss and lasts a lifetime with proper care.',
      'A dental implant is a small titanium post surgically placed in your jawbone that acts as an artificial tooth root. Once it fuses with the bone (a process called osseointegration that takes 3–6 months), a custom porcelain crown is attached on top. The result is virtually indistinguishable from your natural teeth.',
      'Dr. Sarah Chen places and restores implants in-house, which means you work with the same trusted team from start to finish. We use 3D cone beam CT imaging for precise implant placement planning, minimizing risk and optimizing outcomes.',
      'Implants can replace a single tooth, multiple teeth, or even a full arch of teeth. With proper hygiene, a dental implant can last 20–30+ years — many patients keep their implants for life. The investment pays for itself many times over compared to the ongoing costs of dentures or bridges.',
    ],
    startingPrice: '$3,200',
    priceBreakdown: [
      { label: 'Single Implant (post + crown)', price: '$3,200–$5,000' },
      { label: 'Implant Post Only', price: '$1,800–$2,500' },
      { label: 'Implant Crown (on existing post)', price: '$1,200–$1,800' },
      { label: 'Implant-Supported Bridge (3 teeth)', price: '$6,000–$9,000' },
      { label: 'All-on-4 Full Arch', price: '$18,000–$25,000' },
    ],
    whatToExpect: [
      'A comprehensive consultation with 3D CBCT imaging to assess bone volume and plan implant placement.',
      'Any necessary preparatory work (tooth extraction, bone grafting) is performed and healed.',
      'The titanium implant post is surgically placed under local anesthesia — most patients are surprised by how comfortable it is.',
      'A healing period of 3–6 months allows the implant to fuse with the jawbone (osseointegration).',
      'The abutment (connector piece) is attached to the implant post.',
      'Your custom-crafted porcelain crown is placed and adjusted for a perfect bite. Your new tooth is complete.',
    ],
    faqs: [
      { question: 'Is implant surgery painful?', answer: 'The surgery is performed under local anesthesia so you won\'t feel pain during the procedure. Afterward, most patients report discomfort similar to a tooth extraction, manageable with over-the-counter pain medication. Most people return to work the next day.' },
      { question: 'How long do dental implants last?', answer: 'With proper care, implants can last a lifetime. The titanium post is extremely durable and integrates with your bone. The crown on top may need replacement after 15–20 years due to normal wear. Overall, implants have a 95%+ 10-year success rate.' },
      { question: 'Am I a candidate for dental implants?', answer: 'Good candidates have sufficient bone density, healthy gums, and are in general good health. Smokers, uncontrolled diabetics, and patients on certain medications may have reduced success rates. A consultation with 3D imaging will determine your candidacy.' },
      { question: 'How do I care for my implant?', answer: 'Care for implants just like natural teeth — brush twice daily, floss daily, and maintain regular check-ups. There\'s no special maintenance required. You\'ll never need to worry about cavities in the crown, though gum health around the implant remains important.' },
      { question: 'Does insurance cover implants?', answer: 'Many insurance plans now cover a portion of implant costs, particularly if the implant is replacing a tooth lost due to injury or disease. Coverage varies widely — typically $1,000–$1,500 per implant. We\'ll verify your benefits before starting treatment.' },
    ],
  },
  {
    slug: 'emergency-care',
    name: 'Emergency Care',
    category: 'family',
    icon: 'alertcircle',
    shortDescription: 'Same-day emergency appointments for toothaches, broken teeth, lost fillings, and dental trauma.',
    description: [
      'Dental emergencies don\'t wait for a convenient time. Whether you\'ve broken a tooth, lost a crown, developed a severe toothache, or experienced dental trauma, we reserve same-day emergency slots every day so you\'re never left suffering.',
      'Call our emergency line at (512) 555-0199 and we\'ll do our best to see you within hours. For life-threatening emergencies such as difficulty breathing or swallowing, severe jaw swelling, or uncontrolled bleeding, please call 911 or go to the nearest emergency room immediately.',
      'Common dental emergencies we treat include: severe toothache or abscess, broken or cracked teeth, knocked-out or dislodged teeth, lost crowns or fillings, broken dentures or orthodontic appliances, and oral trauma from sports or accidents.',
      'For a knocked-out permanent tooth, time is critical. If you can, place the tooth back in the socket or keep it in milk and call us immediately. Teeth reimplanted within 30 minutes have the best chance of survival.',
    ],
    startingPrice: '$85',
    priceBreakdown: [
      { label: 'Emergency Exam + X-rays', price: '$85–$150' },
      { label: 'Emergency Tooth Extraction', price: '$200–$400' },
      { label: 'Emergency Crown Recementation', price: '$85' },
      { label: 'Emergency Root Canal (front tooth)', price: '$800–$1,100' },
      { label: 'Emergency Root Canal (back tooth)', price: '$1,000–$1,500' },
    ],
    whatToExpect: [
      'Call (512) 555-0199 as soon as you have an emergency — we\'ll find you a same-day slot.',
      'When you arrive, we\'ll take X-rays and assess the situation immediately.',
      'We\'ll explain what\'s happening and present your treatment options with clear pricing.',
      'We provide immediate pain relief as the first priority, then address the underlying issue.',
      'If full treatment can\'t be completed in one visit, we\'ll stabilize the situation and schedule follow-up.',
    ],
    faqs: [
      { question: 'What counts as a dental emergency?', answer: 'A dental emergency is anything causing severe pain, swelling, or bleeding, or risking permanent damage to your teeth. This includes: severe toothache, abscess, broken tooth, knocked-out tooth, lost crown or filling, oral trauma, and swollen jaw or gums.' },
      { question: 'What should I do if a tooth is knocked out?', answer: 'Pick the tooth up by the crown (not the root). If dirty, rinse gently with water — don\'t scrub. Try to reinsert it in the socket or keep it between your cheek and gum or in milk. Call us immediately — the sooner you get in, the better the chance of saving the tooth.' },
      { question: 'What if I have a dental emergency after hours?', answer: 'Call our main line at (512) 555-0142 and follow the prompts to reach our on-call dentist. Our emergency line (512) 555-0199 is available 24/7 for guidance. For severe swelling, difficulty breathing/swallowing, or heavy bleeding, go to the ER immediately.' },
      { question: 'How much does an emergency visit cost?', answer: 'Emergency exams start at $85. Total cost depends on what treatment is needed. We\'ll give you a clear breakdown before doing any work. We accept insurance and offer payment plans — a dental emergency should never go untreated due to cost concerns.' },
    ],
  },
  {
    slug: 'pediatric-dentistry',
    name: 'Pediatric Dentistry',
    category: 'family',
    icon: 'heart',
    shortDescription: 'Gentle, fun dental care for kids of all ages — building healthy habits that last a lifetime.',
    description: [
      'Dr. James Walker, our pediatric specialist, has spent his entire career making dental visits fun and stress-free for children. From a toddler\'s first tooth to a teenager\'s wisdom teeth, we provide comprehensive dental care tailored to every stage of a child\'s development.',
      'Our office has a dedicated kids\' area with age-appropriate entertainment and a team trained in child psychology. We use tell-show-do techniques, positive reinforcement, and age-appropriate language to build trust with young patients and set the foundation for a lifetime of good oral health.',
      'We treat children from their first birthday — the American Academy of Pediatric Dentistry recommends a dental visit by age 1 or when the first tooth appears. Early visits help identify developmental issues, prevent early childhood cavities, and most importantly, help kids feel comfortable at the dentist.',
      'Services for children include first dental exams, preventive cleanings, fluoride treatments, dental sealants, early orthodontic assessment, space maintainers, and tooth-colored fillings. We use the latest techniques to minimize discomfort and maximize cooperation.',
    ],
    startingPrice: '$75',
    priceBreakdown: [
      { label: 'Child\'s First Exam (ages 1–3)', price: '$75' },
      { label: 'Child\'s Cleaning + Exam', price: '$95–$130' },
      { label: 'Fluoride Treatment', price: '$35' },
      { label: 'Dental Sealants (per tooth)', price: '$45–$65' },
      { label: 'Space Maintainer', price: '$350–$500' },
    ],
    whatToExpect: [
      'Dr. Walker greets your child warmly and lets them explore the dental chair and tools before starting.',
      'We count teeth, take any necessary X-rays using child-sized equipment, and check jaw development.',
      'A gentle cleaning removes plaque and tartar, and we apply fluoride treatment if recommended.',
      'Dr. Walker discusses findings with you privately and answers all your questions about your child\'s development.',
      'Your child gets to choose a prize from our treasure chest — making the visit something to look forward to.',
    ],
    faqs: [
      { question: 'When should my child first see a dentist?', answer: 'The American Academy of Pediatric Dentistry recommends a child\'s first dental visit by age 1 or within 6 months of their first tooth appearing. Early visits establish a dental home, allow us to monitor development, and prevent early childhood cavities.' },
      { question: 'How do I prepare my child for their first dental visit?', answer: 'Read books about dental visits, play "dentist" at home, and speak positively about dentists. Bring their favorite toy or comfort item. Avoid using words like "hurt," "needle," or "shot." We do this every day and know how to make kids feel safe.' },
      { question: 'What if my child is anxious or uncooperative?', answer: 'This is completely normal, especially for first visits. Dr. Walker is trained in behavior management techniques and has remarkable patience. In rare cases where anxiety is extreme, we discuss options including nitrous oxide (laughing gas) to help your child relax safely.' },
      { question: 'When should orthodontic evaluation begin?', answer: 'The American Association of Orthodontists recommends a first orthodontic evaluation at age 7. This doesn\'t mean braces at 7 — it allows us to identify issues that are best addressed while the jaw is still growing, potentially simplifying later treatment.' },
    ],
  },
  {
    slug: 'root-canal-therapy',
    name: 'Root Canal Therapy',
    category: 'specialty',
    icon: 'activity',
    shortDescription: 'Modern root canal therapy is virtually painless — we save your natural tooth and eliminate your pain for good.',
    description: [
      'Root canal therapy has an undeserved reputation for being painful. The truth is, root canals relieve pain — they don\'t cause it. With modern anesthesia and techniques, the procedure is no more uncomfortable than a routine filling.',
      'Root canal therapy is needed when the soft inner tissue of a tooth (the pulp) becomes infected or inflamed, usually due to deep decay, a cracked tooth, or trauma. Left untreated, the infection spreads, can lead to abscess, and will ultimately cause tooth loss.',
      'Dr. Sarah Chen uses rotary endodontic instruments and digital X-rays to perform precise, efficient root canal therapy. The infected pulp is removed, the canals are cleaned, shaped, and sterilized, then sealed with a biocompatible material. A crown is typically placed afterward to protect the tooth.',
      'The entire procedure usually takes 60–90 minutes and can often be completed in one appointment. Most patients are surprised by how comfortable they feel during the procedure and return to normal activities the following day. Saving your natural tooth is always the preferred option — it\'s better than any replacement.',
    ],
    startingPrice: '$800',
    priceBreakdown: [
      { label: 'Root Canal – Front Tooth (1 canal)', price: '$800–$1,100' },
      { label: 'Root Canal – Premolar (1–2 canals)', price: '$950–$1,300' },
      { label: 'Root Canal – Molar (3–4 canals)', price: '$1,000–$1,500' },
      { label: 'Crown After Root Canal', price: '$1,200–$1,800' },
      { label: 'Root Canal Retreatment', price: '$1,200–$1,800' },
    ],
    whatToExpect: [
      'The tooth and surrounding area are thoroughly numbed with local anesthesia — you should feel no pain.',
      'A rubber dam is placed around the tooth to keep it dry and prevent contamination.',
      'A small opening is made in the crown of the tooth to access the infected pulp.',
      'The canals are carefully shaped, cleaned, and disinfected using rotary instruments.',
      'The canals are filled and sealed with gutta-percha, a biocompatible rubber material.',
      'A temporary or permanent restoration is placed, and a crown is typically recommended to protect the tooth.',
    ],
    faqs: [
      { question: 'Is a root canal really painful?', answer: 'The root canal procedure itself is not painful when performed under proper anesthesia. You may feel pressure and movement, but not pain. Post-procedure soreness for 2–3 days is normal and managed easily with over-the-counter pain relievers. The pre-procedure infection is what hurts — we\'re fixing that.' },
      { question: 'How long does a root canal take?', answer: 'Most root canals take 60–90 minutes and are completed in a single appointment. Molar root canals with multiple canals or complex anatomy may require two appointments. We\'ll give you an accurate time estimate before starting.' },
      { question: 'Can I drive after a root canal?', answer: 'Yes, if you had local anesthesia only. You should be fine to drive yourself home. If you opted for sedation dentistry, you\'ll need someone to drive you. Plan for a light rest day after your appointment.' },
      { question: 'Do I need a crown after a root canal?', answer: 'In most cases, yes. A root canal removes the tooth\'s blood supply, making it more brittle and susceptible to fracture. A crown protects the tooth and extends its life significantly. Front teeth may sometimes be restored with a filling instead.' },
      { question: 'What happens if I don\'t get a root canal?', answer: 'An infected tooth will not heal on its own. Without treatment, the infection spreads to surrounding teeth, bone, and potentially the jaw or neck in severe cases. The tooth will eventually need extraction. Saving your natural tooth with a root canal is almost always the better option.' },
    ],
  },
]

export const dentists: Dentist[] = [
  {
    id: 'dr-sarah-chen',
    name: 'Dr. Sarah Chen',
    title: 'DDS, Lead Dentist & Founder',
    specialty: 'General & Cosmetic Dentistry',
    bio: 'Dr. Sarah Chen founded Bright Smile Dental in 2012 with a single mission: to deliver big-city dental quality with the warmth of a neighborhood practice. A graduate of the University of Texas School of Dentistry, where she earned her Doctor of Dental Surgery with honors, Dr. Chen has dedicated her career to staying at the forefront of dental technology and technique. She has completed advanced training in cosmetic dentistry, dental implants, and Invisalign at the Las Vegas Institute for Advanced Dental Studies and the Pankey Institute. Outside the clinic, Dr. Chen is a mentor for UT Dental students and volunteers monthly at Austin\'s free dental clinic for underserved communities. When she\'s not perfecting smiles, she enjoys hiking the Barton Creek Greenbelt with her Labrador, Max, and exploring Austin\'s legendary food scene.',
    education: [
      'B.S. Biochemistry, University of Texas at Austin (2005)',
      'Doctor of Dental Surgery (DDS), UT Health San Antonio School of Dentistry (2009)',
      'Advanced Training, Las Vegas Institute for Advanced Dental Studies',
      'Continuing Education, Pankey Institute – Cosmetic & Reconstructive Dentistry',
    ],
    credentials: [
      'American Dental Association (ADA) Member',
      'Texas Dental Association Member',
      'Academy of General Dentistry – Fellow (FAGD)',
      'American Academy of Cosmetic Dentistry Member',
      'Invisalign Certified Provider',
      'CEREC Same-Day Crown Certified',
    ],
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face',
    yearsExperience: 15,
  },
  {
    id: 'dr-james-walker',
    name: 'Dr. James Walker',
    title: 'DMD, Pediatric & Family Dentist',
    specialty: 'Pediatric Dentistry',
    bio: 'Dr. James Walker is the reason why kids at Bright Smile Dental actually look forward to their dental appointments. A board-certified pediatric specialist with a reputation throughout Austin for his extraordinary patience and playful energy, Dr. Walker has a gift for connecting with children of all ages — from anxious toddlers to eye-rolling teens. He completed his pediatric dentistry residency at Dell Children\'s Medical Center in Austin and has been recognized as one of Austin Monthly\'s "Top Dentists" for five consecutive years. Dr. Walker is passionate about early intervention orthodontics, sports dentistry, and eliminating dental anxiety in young patients. He coaches Little League on weekends and is fluent in both English and Spanish, making our practice a welcoming home for Austin\'s diverse families.',
    education: [
      'B.S. Biology, Texas A&M University (2007)',
      'Doctor of Dental Medicine (DMD), Tufts University School of Dental Medicine (2011)',
      'Pediatric Dentistry Residency, Dell Children\'s Medical Center, Austin (2013)',
    ],
    credentials: [
      'American Academy of Pediatric Dentistry (AAPD) Board Certified',
      'Texas Dental Association Member',
      'American Dental Association Member',
      'Austin Monthly Top Dentist – 5 Consecutive Years (2019–2024)',
      'Pediatric Advanced Life Support (PALS) Certified',
      'Fluent in English and Spanish',
    ],
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop&crop=face',
    yearsExperience: 12,
  },
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Jennifer M.',
    rating: 5,
    text: 'I had severe dental anxiety after a bad experience years ago. Dr. Chen was incredibly patient, explained every step, and I actually felt relaxed in the chair. My smile makeover results are beyond what I imagined — I smile in photos for the first time in years. This team changed my life.',
    service: 'Smile Makeover',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face',
    date: 'March 2024',
  },
  {
    id: '2',
    name: 'Marcus T.',
    rating: 5,
    text: 'Same-day emergency appointment when I broke a tooth the morning of an important presentation. They had me in within 2 hours, fixed it beautifully, and I made my meeting looking completely normal. The staff is professional, kind, and genuinely caring. Can\'t recommend them enough.',
    service: 'Emergency Care',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face',
    date: 'January 2024',
  },
  {
    id: '3',
    name: 'Sofia R.',
    rating: 5,
    text: 'Dr. Walker is an absolute miracle worker with my kids. My 7-year-old used to cry for days before any dentist appointment. Now he asks when we\'re going back. They have the perfect balance of being fun and professional. Our whole family comes here and we wouldn\'t go anywhere else.',
    service: 'Pediatric Dentistry',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face',
    date: 'February 2024',
  },
  {
    id: '4',
    name: 'Robert & Diane K.',
    rating: 5,
    text: 'We moved to Austin two years ago and finding Bright Smile Dental was one of the best things that happened. Dr. Chen is thorough, honest, and never recommends unnecessary treatment. After years of being overtreated at our last dentist, this level of integrity is refreshing. Clean office, no wait times, perfect experience.',
    service: 'General Dentistry',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop&crop=face',
    date: 'April 2024',
  },
  {
    id: '5',
    name: 'Priya N.',
    rating: 5,
    text: 'I finished my Invisalign treatment in 14 months and the results are stunning. Dr. Chen showed me a digital preview on day one, so I knew exactly what to expect. The whole process was smooth, comfortable, and the team kept me motivated. My confidence has completely transformed.',
    service: 'Invisalign',
    image: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&h=100&fit=crop&crop=face',
    date: 'May 2024',
  },
  {
    id: '6',
    name: 'David L.',
    rating: 5,
    text: 'Had a dental implant placed last year and I genuinely cannot tell which tooth is the implant — it\'s perfect. The process was very well explained, the surgery was completely comfortable, and the follow-up care was excellent. Worth every penny. Should have done this years ago.',
    service: 'Dental Implants',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
    date: 'December 2023',
  },
]

export const timeSlots = [
  '8:00 AM', '8:30 AM', '9:00 AM', '9:30 AM', '10:00 AM', '10:30 AM',
  '11:00 AM', '11:30 AM', '1:00 PM', '1:30 PM', '2:00 PM', '2:30 PM',
  '3:00 PM', '3:30 PM', '4:00 PM', '4:30 PM', '5:00 PM',
]
